Algoritmo "Codigo 02"
// Descrição   : Convertendo para caixa-alta
// Autor(a)    : Emanuel Vital Falcão
// Data atual  : 04/07/2022
Var
// Seção de Declarações das variáveis 
valor : caractere
convertida : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite uma palavra ou frase")
leia(valor)
convertida <- maiusc(valor)
escreva (convertida)

Fimalgoritmo