Algoritmo "Codigo 01"
// Descrição   : Convertendo número em caractere
// Autor(a)    : Emanuel Vital Falcão
// Data atual  : 04/07/2022
Var
// Seção de Declarações das variáveis 
numero : inteiro
convertido : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um número:")
leia(numero)
convertido <- NumpCarac(numero)
escreval("O número convertido para caractere é ", convertido)

Fimalgoritmo