Algoritmo "Codigo 03"
// Descrição   : Contando os caracteres da string
// Autor(a)    : Emanuel Vital Falcão
// Data atual  : 04/07/2022
Var
// Seção de Declarações das variáveis 
palavra : caractere
comprimento : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite uma palavra:")
leia(palavra)
comprimento <- Compr(palavra)
escreval ("A palavra ", palavra, " possui ", comprimento, " caracteres")

Fimalgoritmo